### ISSUE TITLE
现在nhimmeo的每一章节都需要单独加载一段时间，导致爬虫不了

### ISSUE THREAD

**Issue by gin32167** [phantom-sea-limited/Crawler#10]
### 是否有已经存在的问题

- [X] 我已经查阅了 https://github.com/phantom-sea-limited/Crawler/issues
- [X] 我正在使用最新版的爬虫

### 是什么爬虫引发的问题

nhimmeo.user.js

### 你在哪个网页遇到的问题

https://zh.nhimmeo.cf/chap/111035139

### 描述问题

现在nhimmeo的每一章节都先显示loading，加载一段时间才显示内容，爬虫会直接略过，导致下载不了

### 其他

<img width="945" alt="001" src="https://github.com/phantom-sea-limited/Crawler/assets/83170209/fd2dc0dc-3af0-4e80-84fc-1546577206d3">
如图，现在nhimmeo的每一章节都需要单独加载一段时间，导致爬虫不了

**Comment by Rcrwrate** [comment]
已经试图修复，如还有问题请告知我，如没有，可以close issue

**Comment by gin32167** [comment]
可以下载了，不过下载的文件，格式挤做了一团，没有分段
<img width="984" alt="001" src="https://github.com/phantom-sea-limited/Crawler/assets/83170209/25c3a9a8-14e3-492d-a24a-b9332664ed81">

**Comment by Rcrwrate** [comment]
能否直接提供一下生成的json文件或者epub

**Comment by gin32167** [comment]
[椎名真白的实力主义至上教室.json](https://github.com/phantom-sea-limited/Crawler/files/13933996/default.json)

**Comment by Rcrwrate** [comment]
已经修复，不过出错的文件已经不可逆了，请记得清空该书的缓存

**Comment by gin32167** [comment]
现在下载后的格式正常了，但是部分章节下载的时候，会重复下载，终止任务导出文件，发现那些章节虽然重复下载几遍，但是没有内容，可能是没加载就下载了，然后又重复这个操作。例如下面这本书的68-90章节。

https://zh.nhimmeo.cf/book/100379363

**Comment by Rcrwrate** [comment]
理论上而言，如果某个章节（页面）加载超时了还没加载完成，会有一个机制去进行一个页面刷新，然后这个章节的任务就会被跳过，但是最任务末尾会进行一个检查，检查是否有遗漏的章节

你也可以通关在数据页面点击**修复下载**进行强制修复，修复完在点击**手动导出**即可

**Comment by gin32167** [comment]
修复下载也不行，还是会在那几个章节不停的重复，每个章节刚进入就立刻切换下一章节，终止任务后导出，章节依然没有内容

**Comment by Rcrwrate** [comment]
提供一下控制台的信息，记得勾选保留日志

![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/72c0ae87-de03-45fc-9d1a-1811162c44ac)

**Comment by gin32167** [comment]
[日志.zip](https://github.com/phantom-sea-limited/Crawler/files/14000668/default.zip)

**Comment by Rcrwrate** [comment]
能不能再次提供一下手动导出之后的json文件，我在我这测试一下看看

**Comment by gin32167** [comment]
[导出.zip](https://github.com/phantom-sea-limited/Crawler/files/14005710/default.zip)

**Comment by Rcrwrate** [comment]
测试了一下，应该是网络的问题
![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/72543b34-bb28-4f2d-8bdc-d43011f2083f)

我将超时时间调整为一分钟

**Comment by gin32167** [comment]
可以成功下载了，谢谢
