### ISSUE TITLE
py脚本无法打包成EPUB

### ISSUE THREAD

**Issue by Curtaun** [phantom-sea-limited/Crawler#11]
### 是否有已经存在的问题

- [X] 我已经查阅了 https://github.com/phantom-sea-limited/Crawler/issues
- [X] 我已经查阅了互联网，但并没有得到解决方案

### 描述问题

这是还缺少什么依赖吗？

### 其他

![image](https://github.com/phantom-sea-limited/Crawler/assets/30548071/a5218849-5048-4d75-bf65-ac880f18a233)

**Comment by Rcrwrate** [comment]
把整个仓库都下下来，或者把仓库目录Lib里的文件下下来，**保持目录结构一致**

![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/8790816c-1660-46eb-b0f7-5d7371c5557d)

**Comment by Rcrwrate** [comment]
文档下次提交的时候改，
Unicode码很神秘，我不是很清楚
Epub打包脚本是数一数二的暴力解决方案，如果你有更好的方案，方便PR一下吗
![3KLAR)Y FE8 O}}X(43K274](https://github.com/phantom-sea-limited/Crawler/assets/46920034/4dc88f63-71d9-4ff8-b5bf-71645d59883d)
