### ISSUE TITLE
Unicode过滤范围过大了

### ISSUE THREAD

**Issue by jiafjioajfijaiofnkan** [phantom-sea-limited/Crawler#14]
可以打包了，建议在文档里说明需要下载整个仓库而不是单文件，另外nhimmeo的py脚本打包还是有问题，有很多Unicode码没被过滤，直接改成用[\u0000-\u10FFFF]匹配可行吗

_Originally posted by @Curtaun in https://github.com/phantom-sea-limited/Crawler/issues/11#issuecomment-1891391597_
            
发现数字被过滤了，追查最新的commit发现了这里，连ASCII都被过滤掉了，范围过大了。
测试代码：
```python
import re
k="123分456秒"
print(re.sub(r'[\u0000-\u10FFFF]', " ", k))
#   分  秒
```
目前我是改成\u0100起步，后面得根据Unicode平面选择过滤掉的基本面。

**Comment by Rcrwrate** [comment]
Unicode这东西我还真的不是很想管，处理起来也不是很难，改回来了，只过滤`\u3000`

后来新的Unicode应该是nhimmeo加解密的问题

![NI 0FZ96{SLA@J27_`JI Y6](https://github.com/phantom-sea-limited/Crawler/assets/46920034/09174066-c2a3-45fb-91c0-1dbb9c8ad760)
