### ISSUE TITLE
nhimmeo网址变了，下载工具用不了

### ISSUE THREAD

**Issue by k88621** [phantom-sea-limited/Crawler#18]
现网址：https://zh.nhimmeo.ovh/

**Comment by gin32167** [comment]
使用旧的地址能继续登录，并且下载工具也能继续用

**Comment by Rcrwrate** [comment]
其实应该只需要你对脚本查找替换zh.nhimmeo.cf为zh.nhimmeo.ovh就行了

虽然说晚了点，但是好像是好了
