### ISSUE TITLE
[Qestion] nhimmeo脚本能否进行增量下载？

### ISSUE THREAD

**Issue by svtxkbxxeey3935** [phantom-sea-limited/Crawler#2]
# 开头
我在看了脚本的功能界面和[高级说明](https://github.com/phantom-sea-limited/Crawler/blob/main/nhimmeo.md)后，并没有找到能从某章开始下载，或类似的功能

# 描述
在nhimmeo上逐页爬取是一件相当费时的事情，尤其是在那种已经有几百章内容的小说。

比如，在已经下载过一次300章内容小说的情况下，我完全没有必要为了30章的更新，重新下一遍重复的300章内容。

相比手动合并新下载的30章内容所增加的一点时间，直接从300章后开始下载，更能极大的节省时间，原网站也能节省带宽。

**Comment by Rcrwrate** [comment]
好的，预计在明天处理，请稍等

> sangtacviet.vip.user.js已经支持增量更新

**Comment by Rcrwrate** [comment]
已完工，我这边测试没有问题，如果有问题，回复即可，没问题可以close

**Comment by svtxkbxxeey3935** [comment]
> 已完工，我这边测试没有问题，如果有问题，回复即可，没问题可以close

辛苦大佬更新。

唯一的问题是，如果我下载的云端文件，本地就不会有事先产生的缓存。

是不是可以主动指定前xxx章忽略下载，尽管指定的数字跟实际章节号肯定对不上，但这依旧能排除大部分的重复缓存

**Comment by Rcrwrate** [comment]
> > 已完工，我这边测试没有问题，如果有问题，回复即可，没问题可以close
> 
> 辛苦大佬更新。
> 
> 唯一的问题是，如果我下载的云端文件，本地就不会有事先产生的缓存。
> 
> 是不是可以主动指定前xxx章忽略下载，尽管指定的数字跟实际章节号肯定对不上，但这依旧能排除大部分的重复缓存

~~啊？我说实话有点没理解，啊，我好像又理解了~~

云端文件下载完成之后会自己直接替换本地的缓存，原本的缓存会被抛弃，本地缓存存不存在都不影响，其实就是为了方便用户进行快速下载

重复缓存的话，实际上不会存在重复缓存的问题，云端永远只会一本书对应一个文件（每一次上传都是对这个文件的更新，会产生一个新的版本），我后期会去做一个文件版本的选择下载

云空间可大了，莫慌，小事
