### ISSUE TITLE
nhimmeo下载下来的json文件使用nhimmeo.py显示缺少json文件

### ISSUE THREAD

**Issue by qiannianmo** [phantom-sea-limited/Crawler#22]
### 是否有已经存在的问题

- [X] 我已经查阅了 https://github.com/phantom-sea-limited/Crawler/issues
- [X] 我已经查阅了互联网，但并没有得到解决方案

### 描述问题

nhimmeo下载下来的json文件使用nhimmeo.py显示缺少json文件

**Comment by Rcrwrate** [comment]
使用方式是`python nhimmeo.py 10053432.json`，10053432是你的书籍ID，此处为举例

**Comment by qiannianmo** [comment]
> 使用方式是`python nhimmeo.py 10053432.json`，10053432是你的书籍ID，此处为举例
win11是在win+R cmd里使用吗

**Comment by Rcrwrate** [comment]
任意终端都可以

**Comment by Rcrwrate** [comment]
你可以在文件管理器空白处按住shift右键
![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/16879b2b-fb13-4bf1-93b5-d81cccea4203)
