### ISSUE TITLE
Qidian VIP chapters are fixed

### ISSUE THREAD

**Issue by BanQuyY** [phantom-sea-limited/Crawler#24]
### 是否有已经存在的问题

- [X] 我已经查阅了 https://github.com/phantom-sea-limited/Crawler/issues
- [X] 我正在使用最新版的爬虫

### 是什么爬虫引发的问题

sangtacviet.user.js

### 你在哪个网页遇到的问题

https://sangtacviet.com

### 描述问题

无法在 sangtacviet.com 上下载 VIP 章节，VIP 章节仍可手动查看

### 其他

https://sangtacviet.com/truyen/qidian/1/1040713239/

**Comment by Kaizo2004** [comment]
I have the same problem

**Comment by Rcrwrate** [comment]
请稍等，我看一下

**Comment by Rcrwrate** [comment]
更新一下脚本，如果还有问题的话，请继续回复，没问题的话，请close issue
![@VVL`7B) 7CQ~%7S7~R} 0H](https://github.com/user-attachments/assets/5d28b227-7d1a-46c2-83f8-8540d0efb028)
