### ISSUE TITLE
在网站zh.nhimmeo.cf上无法爬取内容

### ISSUE THREAD

**Issue by haicao8848** [phantom-sea-limited/Crawler#4]
在可以爬取的时间内尝试用nhimmeo下载工具对zh.nhimmeo.cf网站爬取，点击“下载”或“修复下载”右下角开始出现爬取章节，自动打开第一章后便没有了反应，如果回到书籍首页，会自动打开第一章节但是没有反应，不会下一章
故障图片：
![QQ截图20231216025446](https://github.com/phantom-sea-limited/Crawler/assets/81633083/743215b1-a19b-431a-b421-99305e5887e6)
![QQ截图20231216025458](https://github.com/phantom-sea-limited/Crawler/assets/81633083/7c05043c-0e54-4a9a-957a-c05be8690d6e)
![QQ截图20231216025624](https://github.com/phantom-sea-limited/Crawler/assets/81633083/0e0140c6-5a1e-4c0f-842a-32e5cc3c7ce8)

顺便问一下Rcrwrate，zh.nhimmeo.cf有了个更稳定的网站nextjs.nhimmeo.ovh，有考虑做nextjs.nhimmeo.ovh网站的下载器吗？.zh的爬取太容易崩溃了：(
我也试过直接改网址看看能不能直接适用，结果看来是不行:(

**Comment by haicao8848** [comment]
问题爬取不会自动下一章了

**Comment by Rcrwrate** [comment]
相关问题，已修复，如没问题，可以close issue

**Comment by haicao8848** [comment]
> 相关问题，已修复，如没问题，可以close issue

还是不行，下载之类的按钮也没有，在不能下载的时间打开页面也没有提示不能再12点以后下载这种提示
![ZHEMS429Z_(J5P3FPAW0HKD](https://github.com/phantom-sea-limited/Crawler/assets/81633083/80545562-da6a-423a-9d30-9a55aa3bf925)

**Comment by Rcrwrate** [comment]
设计失误，抱歉
