### ISSUE TITLE
目录排列不正确

### ISSUE THREAD

**Issue by BanQuyY** [phantom-sea-limited/Crawler#5]
![image](https://github.com/phantom-sea-limited/Crawler/assets/117709394/4b29ab3e-7788-4786-904e-827b2a28c323)

**Comment by Rcrwrate** [comment]
能否直接提供一下源文件

**Comment by BanQuyY** [comment]
https://sangtacviet.vip/truyen/qidian/1/1037477715/

**Comment by Rcrwrate** [comment]
目录排序问题已找到，来源于起点官方的问题，起点的章节排序不按照章节ID进行

会和额外支持一同完成

**Comment by Rcrwrate** [comment]
![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/c501ef36-081d-41cb-a958-0d42b3cd9e94)

[领主降临：诸神璀璨时代.json](https://github.com/phantom-sea-limited/Crawler/files/13775879/default.json)

已经修复,额外支持也已经添加

如有问题请继续说明，如没问题可以close issue

**Comment by BanQuyY** [comment]
负载无限循环
Sangtacviet.com

**Comment by Rcrwrate** [comment]
在哪里循环，怎么个循环，请详细描述

**Comment by BanQuyY** [comment]
1-7 for

**Comment by Rcrwrate** [comment]
?，这是正常现象，脚本就是这么爬内容的

这是一个历史问题，最开始这个脚本就是设计为 **物理上绕过防火墙** 在前端爬取数据

今天我才发现，可以直接爬

**Comment by BanQuyY** [comment]
无法下载章节。
希望可以修复🤣
