### ISSUE TITLE
 汉化工具使不成

### ISSUE THREAD

**Issue by zwgfd** [phantom-sea-limited/Crawler#6]
你需要在 sangtacviet.com 下使用本功能汉化工具使不成

**Comment by Rcrwrate** [comment]
需要在具体章节下使用汉化工具

比如[这个章节](https://sangtacviet.com/truyen/qidian/1/1037477715/763924634/)

**Comment by zwgfd** [comment]
> 需要在具体章节下使用汉化工具
> 
> 比如[这个章节](https://sangtacviet.com/truyen/qidian/1/1037477715/763924634/)

大佬汉化工具用不成

**Comment by zwgfd** [comment]
![微信图片_20231229154519](https://github.com/phantom-sea-limited/Crawler/assets/154878936/5494780a-f9ff-467b-a279-4ecdb0a1d8cc)
![微信图片_20231229154612](https://github.com/phantom-sea-limited/Crawler/assets/15487893
![微信图片_20231229154618](https://github.com/phantom-sea-limited/Crawler/assets/154878936/9af12d56-6186-44f7-a742-6a331c201e7d)
6/93a3fdd8-2522-4725-81ab-1918b08f1279)

**Comment by Rcrwrate** [comment]
请确保你使用的版本为最新版`2.1.3`

我这里没有任何问题

**Comment by zwgfd** [comment]
> 请确保你使用的版本为最新版`2.1.3`
> 
> 我这里没有任何问题
> 
> 请把出问题的页面地址发出来
大佬章节都是图片这样
![微信图片_20231231161944](https://github.com/phantom-sea-limited/Crawler/assets/154878936/997fe97d-5b80-4a01-8d83-7229d863d62d)
![微信图片_20231231161618](https://github.com/phantom-sea-limited/Crawler/assets/154878936/a9dd1157-75e0-4117-9c83-c409947428c8)
@Rcrwrate

**Comment by Rcrwrate** [comment]
![image](https://github.com/phantom-sea-limited/Crawler/assets/46920034/a97e6f1f-0c03-490d-9bbf-ff7aced1b09a)

请确保图示位置内容等于`sangtacviet.com`，而不是`sangtacviet.vip`，如果不等于，请直接手动修改之后按回车键

**Comment by zwgfd** [comment]
大佬好了.章节缺字
![微信图片_20240101194334](https://github.com/phantom-sea-limited/Crawler/assets/154878936/367a1e91-b30c-489f-ba7e-c49c70d25ac6)
![微信图片_20240101204105](https://github.com/phantom-sea-limited/Crawler/assets/154878936/c30c835e-bfb6-4a1e-b910-e1632bfbb05e)

![微信图片_20240101194334](https://github.com/phantom-sea-limited/Crawler/assets/154878936/f2af8769-5093-4024-bd8e-ee12426b996e)

**Comment by Rcrwrate** [comment]
这个是源头的问题，不是脚本的问题

**Comment by zwgfd** [comment]
> 这个是源头的问题，不是脚本的问题

谢谢

**Comment by Rcrwrate** [comment]
如果还有新问题请新开issue，这个issue我就关闭了
