### ISSUE TITLE
在网站sangtacviet.com使用，不断重复任务

### ISSUE THREAD

**Issue by 007MZY0524** [phantom-sea-limited/Crawler#7]
环境：ubuntu22.04，edge/火狐
位置：https://sangtacviet.com/truyen/ciweimao/1/100385563/

爬取至最后一章时任务剩余数不为0，重新开始爬取并重置任务剩余数，不断循环。手动终止任务，导出文件并不包含章节内内容

**Comment by Rcrwrate** [comment]
可以先尝试使用清空缓存

你有没有多次点击过下载等按钮

我这边sangtacviet不知道为什么章节内容加载不出来

**Comment by Rcrwrate** [comment]
问题找到了，这个问题只会在sangtacviet.com出现，修复会稍后和其他内容一同推送

**Comment by 007MZY0524** [comment]
> 问题找到了，这个问题只会在 sangtacviet.com 出现，修复会稍后和其他内容一同推送

阿里噶多
