### ISSUE TITLE
nhimmeo.py拖进pythonw好像报错了

### ISSUE THREAD

**Issue by 2477138580** [phantom-sea-limited/Crawler#8]
不知道是不是我使用方式有问题
![QQ图片20231229044218](https://github.com/phantom-sea-limited/Crawler/assets/95111161/89bb470e-eb4f-4519-b6a7-34095c97662f)

**Comment by Rcrwrate** [comment]
直接在该文件夹空白处按住shift+右键

点击在此处打开powershell窗口或者是在终端打开

然后就是正常输入`python nhimmeo.py ****.json`

**Comment by 2477138580** [comment]
![QQ图片20231230012333](https://github.com/phantom-sea-limited/Crawler/assets/95111161/ae5caf6a-ed5e-4475-af4c-9759294628c1)

**Comment by 2477138580** [comment]
而且zh.nhimmeo.cf的下载插件貌似无限循环下载了

**Comment by 2477138580** [comment]
甚至还有邮件大佬真是我哭死（&nbsp;


11123123a
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月29日(星期五) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [phantom-sea-limited/Crawler] nhimmeo.py拖进pythonw好像报错了 (Issue #8)





 
直接在该文件夹空白处按住shift+右键
 
点击在此处打开powershell窗口或者是在终端打开
 
然后就是正常输入python nhimmeo.py ****.json

**Comment by Rcrwrate** [comment]
有没有更多的信息，截图、录屏

否则，我无法判断问题
